services:
  mariadb:
    image: mariadb:10.11
    container_name: tpa-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpa_db
      MYSQL_USER: tpa_user
      MYSQL_PASSWORD: tpa_password
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mariadb:/var/lib/mysql