spring.application.name: tpa-sun-core-api
#spring.profiles.active: local-dev
spring:
  application:
  config:
    import:
      - optional:file:.env[.properties]
      - db-core.yml
  web.resources.add-mappings: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 3600
  refresh-token-expiration: 1209600
minio:
  endpoint: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: tpa-sun
  region: ap-northeast-2

---
spring:
  config:
    activate:
      on-profile: local
  docker:
    compose:
      enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
# JWT 설정
jwt:
  secret-key: "VGhpc0lzQVRlc3RTZWNyZXRLZXlGb3JKd3RUb2tlbkdlbmVyYXRpb25BbmRJdElzTG9uZ0Vub3VnaA=="
  access-token-expiration: 3600
  refresh-token-expiration: 1209600

---
spring:
  config:
    activate:
      on-profile: local-dev
  jmx:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 3600
  refresh-token-expiration: 1209600
minio:
  endpoint: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: tpa-sun
  region: ap-northeast-2

---
spring:
  config:
    activate:
      on-profile: staging

---
spring:
  config:
    activate:
      on-profile: live